---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32090
      protocol: TCP
  selector:
    app: server