---
apiVersion: v1
kind: Service
metadata:
  name: indexer
  labels:
    app: indexer
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
      protocol: TCP
  selector:
    app: indexer