apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: indexer
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: indexer
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metricName: http_requests
      targetAverageValue: 10