# Nats config
NATSAddress = "nats://nats-cluster.nats-io:4222"
Topic = "flight-crashes-with-coords"

# ElasticSearch config
Elastics = [ "http://elasticsearch.elastic:9200" ]

# HTTP config
HTTPPort = 8080
GracefulShutdownTimeout = 10