---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32222
      protocol: TCP
  selector:
    app: ui