# Nats config
NATSAddress = "nats://192.168.99.100:32201"
Topic = "flight-crashes"
OutTopic = "flight-crashes-with-coords"
QueueGroup = "consumer-group"

# ElasticSearch config
Elastics = [ "http://192.168.99.100:32000" ]
BulkSize = 10

# HTTP config
HTTPPort = 8080
GracefulShutdownTimeout = 10