apiVersion: batch/v1
kind: Job
metadata:
  name: auto-ingress
spec:
  template:
    spec:
      containers:
      - name: auto-ingress
        image: index.docker.io/mateuszdyminski/auto-ingress:latest
      restartPolicy: Never
  backoffLimit: 4
